import { Product } from './types';

export const PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Lumina Noise-Canceling Headphones',
    price: 299.99,
    category: 'Electronics',
    description: 'Immerse yourself in pure audio bliss with our flagship noise-canceling headphones. Featuring adaptive sound control and 30-hour battery life.',
    image: 'https://picsum.photos/id/1/800/800',
    rating: 4.8,
    reviews: 124,
    features: ['Active Noise Cancellation', '30hr Battery', 'Bluetooth 5.2'],
    stock: 15,
  },
  {
    id: '2',
    name: 'Minimalist Analog Watch',
    price: 149.50,
    category: 'Accessories',
    description: 'A timeless piece for the modern individual. Swiss movement encased in brushed stainless steel with a genuine leather strap.',
    image: 'https://picsum.photos/id/175/800/800',
    rating: 4.5,
    reviews: 89,
    features: ['Swiss Movement', 'Water Resistant', 'Sapphire Glass'],
    stock: 42,
  },
  {
    id: '3',
    name: 'Ergonomic Mesh Office Chair',
    price: 349.00,
    category: 'Home',
    description: 'Work in comfort with our breathable mesh chair designed to support your posture during long hours. Fully adjustable lumbar support.',
    image: 'https://picsum.photos/id/1068/800/800',
    rating: 4.7,
    reviews: 210,
    features: ['Lumbar Support', 'Breathable Mesh', 'Heavy Duty Base'],
    stock: 8,
  },
  {
    id: '4',
    name: 'Smart Home Speaker Hub',
    price: 99.99,
    category: 'Electronics',
    description: 'Control your entire home with your voice. High-fidelity sound meets intelligent home automation in a sleek fabric-wrapped design.',
    image: 'https://picsum.photos/id/39/800/800',
    rating: 4.6,
    reviews: 532,
    features: ['Voice Control', 'Smart Hub', '360 Audio'],
    stock: 120,
  },
  {
    id: '5',
    name: 'Organic Cotton Crewneck',
    price: 45.00,
    category: 'Fashion',
    description: 'Ethically sourced and incredibly soft. This essential crewneck sweatshirt is perfect for layering or lounging.',
    image: 'https://picsum.photos/id/1005/800/800',
    rating: 4.9,
    reviews: 76,
    features: ['100% Organic Cotton', 'Pre-shrunk', 'Sustainable Dye'],
    stock: 200,
  },
  {
    id: '6',
    name: 'Ceramic Pour-Over Set',
    price: 65.00,
    category: 'Home',
    description: 'Elevate your morning ritual. Hand-crafted ceramic dripper and carafe for the perfect bloom and brew every time.',
    image: 'https://picsum.photos/id/425/800/800',
    rating: 4.8,
    reviews: 45,
    features: ['Hand-glazed', 'Heat Retentive', 'Dishwasher Safe'],
    stock: 25,
  },
  {
    id: '7',
    name: 'Leather Weekend Bag',
    price: 225.00,
    category: 'Fashion',
    description: 'Rugged yet refined. Full-grain leather duffel bag spacious enough for a weekend getaway, durable enough for a lifetime.',
    image: 'https://picsum.photos/id/1011/800/800',
    rating: 4.7,
    reviews: 32,
    features: ['Full-grain Leather', 'Brass Hardware', 'Laptop Compartment'],
    stock: 12,
  },
  {
    id: '8',
    name: 'Wireless Mechanical Keyboard',
    price: 120.00,
    category: 'Electronics',
    description: 'Tactile satisfaction without the wires. Hot-swappable switches and RGB backlighting in a compact 65% layout.',
    image: 'https://picsum.photos/id/366/800/800',
    rating: 4.9,
    reviews: 156,
    features: ['Mechanical Switches', 'RGB Backlight', 'Multi-device Pair'],
    stock: 30,
  },
];

export const MOCK_PRICE_HISTORY = [
  { name: 'Jan', price: 280 },
  { name: 'Feb', price: 290 },
  { name: 'Mar', price: 285 },
  { name: 'Apr', price: 295 },
  { name: 'May', price: 299.99 },
  { name: 'Jun', price: 310 },
  { name: 'Jul', price: 299.99 },
];
